#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus-inst
- name: Create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    shell: /sbin/nologin

- name: Download Prometheus tarball
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Move Prometheus binaries
  copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: yes
    mode: '0755'
  loop:
    - prometheus
    - promtool

- name: Create Prometheus config and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Copy Prometheus config
  copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
    dest: "/etc/prometheus/prometheus.yml"
    remote_src: yes

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus

      [Install]
      WantedBy=multi-user.target
  notify: Restart Prometheus
