#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-inst
# Install docker
- name: Install docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes

- name: Enable and start the docker
  systemd:
    name: docker
    enabled: yes
    state: started

